spring.application.name=desafio-itau
springdoc.swagger-ui.path=/
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
estatistica.tempo-limite=${ESTATISTICA_TEMPO_LIMITE:60}